name: CI/CD Pipeline Sama-Docteur

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    name: Build & Push Images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push API
        uses: docker/build-push-action@v4
        with:
          context: ./api
          push: true
          tags: mohamedloum1001/sama-docteur-api:latest

      - name: Build and Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: mohamedloum1001/sama-docteur-frontend:latest
          build-args: |
            REACT_APP_FIREBASE_API_KEY=${{ secrets.REACT_APP_FIREBASE_API_KEY }}
            REACT_APP_FIREBASE_AUTH_DOMAIN=${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}
            REACT_APP_FIREBASE_PROJECT_ID=${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}
            REACT_APP_FIREBASE_STORAGE_BUCKET=${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}
            REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}
            REACT_APP_FIREBASE_APP_ID=${{ secrets.REACT_APP_FIREBASE_APP_ID }}
            REACT_APP_STRIPE_PUBLISHABLE_KEY=${{ secrets.REACT_APP_STRIPE_PUBLISHABLE_KEY }}

  # deploy:
  #   name: Continuous Deployment to Production
  #   needs: build-and-push
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy to Server via SSH
  #       uses: appleboy/ssh-action@v0.1.10
  #       with:
  #         host: ${{ secrets.PRODUCTION_HOST }}
  #         username: ${{ secrets.PRODUCTION_USERNAME }}
  #         key: ${{ secrets.PRODUCTION_SSH_KEY }}
  #         port: 22
  #         script: |
  #           echo "Connexion SSH réussie au serveur de production."

            # 1. Se positionner dans le répertoire du projet
            # cd /var/www/sama-docteur

            # # 2. Récupérer les dernières configurations (ex: docker-compose actualisé)
            # git pull origin main

            # # 3. Récupérer les nouvelles images depuis Docker Hub
            # docker compose pull

            # # 4. Relancer les conteneurs avec les nouvelles versions sans interruption de service
            # docker compose up -d --remove-orphans

            # # 5. Nettoyage des anciennes images inutilisées pour économiser de l'espace disque
            # docker image prune -f

            # echo "Déploiement continu terminé avec succès !"
